wsentence=input("Please enter a sentence")
print(wsentence)
def wordcount():
    print(int(wsentence.count(' ')+1))
print(wordcount)

input("Press Enter to start MadLibs:")
name=input("Please enter your/a name:")
weather=input("Please enter a weather condition:")
noun1=input("Please enter a noun:")
noun2=input("Please enter another noun:")
verb1=input("Please enter a verb:")
verb2=input("Please enter another verb:")
number=input("Please enter a number:")
celebrity=input("Please enter a celebrity to cameo in your story (preferably the Rock):")
input("Now, lets see what you've created:")
print(name, "was sleeping under a tree on a", weather, "day. Suddenly, a",  verb1, noun1,"and a", verb2, noun2 "appeared out of nowhere. After a while, the", verb1, noun1, "had started to a dance. This dance annoyed the,", verb2, noun2, "causing them to engage in a dance battle with you as the judge. Just a second, said a voice in the distance. As they came closer you started to make out the shape. It was", celebrity, "! I will help judge this intense dance battle.", noun)